name: WorldEssentials
version: "${pom.version}"
api: ["1.0.11"]
author: Scallop, PetteriM1
main: idk.plugin.worldessentials.WorldEssentials

permissions:
 worldessentials.command.setworldgamemode:
  description: "Allows the user to set a world's default gamemode"
  default: op
